import Foundation

/// The slice of app state generated by the user — everything a real backend would sync.
/// Kept as a flat Codable snapshot so the whole thing round-trips through one JSON file.
struct PersistedState: Codable {
    var onboardingComplete: Bool = false
    var rankings: [RankingEntry] = []
    var visits: [RestaurantVisit] = []
    var wantToTryIDs: [String] = []
    var friendIDs: [String] = []
    var comparisonCount: Int = 0
    var groupRecCount: Int = 0
    /// achievementID -> unlock date.
    var unlockedAchievements: [String: Date] = [:]
    var featuredAchievementIDs: [String] = []
    var likedActivityIDs: [String] = []
    /// The current user's (drifting) preference vector.
    var preferences: TasteVector? = nil
    var challenges: [Challenge] = []
    var feed: [SocialActivity]? = nil
    var restaurants: [Restaurant]? = nil
    var cities: [City]? = nil
    var user: User? = nil
}

/// Loads/saves `PersistedState`. A thin protocol keeps the door open for a real
/// networked backend later; `FilePersistenceService` is the local implementation.
protocol PersistenceService {
    func load() throws -> PersistedState?
    func save(_ state: PersistedState) throws
    func reset() throws
}

/// JSON-file persistence in the app's Documents directory.
final class FilePersistenceService: PersistenceService {
    private let url: URL

    init(filename: String = "bite_live_state.json", directory: URL? = nil) {
        let docs = directory ?? FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0]
        url = docs.appendingPathComponent(filename)
    }

    func load() throws -> PersistedState? {
        guard FileManager.default.fileExists(atPath: url.path) else { return nil }
        return try JSONDecoder().decode(PersistedState.self, from: Data(contentsOf: url))
    }

    func save(_ state: PersistedState) throws {
        let data = try JSONEncoder().encode(state)
        try FileManager.default.createDirectory(at: url.deletingLastPathComponent(), withIntermediateDirectories: true)
        try data.write(to: url, options: [.atomic, .completeFileProtectionUntilFirstUserAuthentication])
    }

    func reset() throws {
        if FileManager.default.fileExists(atPath: url.path) { try FileManager.default.removeItem(at: url) }
    }
}
