import Foundation

/// The slice of app state generated by the user — everything a real backend would sync.
/// Kept as a flat Codable snapshot so the whole thing round-trips through one JSON file.
struct PersistedState: Codable {
    var onboardingComplete: Bool = false
    var rankings: [RankingEntry] = []
    var visits: [RestaurantVisit] = []
    var wantToTryIDs: [String] = []
    var friendIDs: [String] = []
    var comparisonCount: Int = 0
    var groupRecCount: Int = 0
    /// achievementID -> unlock date.
    var unlockedAchievements: [String: Date] = [:]
    var featuredAchievementIDs: [String] = []
    var likedActivityIDs: [String] = []
    /// The current user's (drifting) preference vector.
    var preferences: TasteVector? = nil
    var challenges: [Challenge] = []
}

/// Loads/saves `PersistedState`. A thin protocol keeps the door open for a real
/// networked backend later; `FilePersistenceService` is the local implementation.
protocol PersistenceService {
    func load() -> PersistedState?
    func save(_ state: PersistedState)
    func reset()
}

/// JSON-file persistence in the app's Documents directory.
final class FilePersistenceService: PersistenceService {
    private let url: URL
    private let queue = DispatchQueue(label: "com.bite.persistence")

    init(filename: String = "bite_state.json") {
        let docs = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0]
        url = docs.appendingPathComponent(filename)
    }

    func load() -> PersistedState? {
        guard let data = try? Data(contentsOf: url) else { return nil }
        return try? JSONDecoder().decode(PersistedState.self, from: data)
    }

    func save(_ state: PersistedState) {
        queue.async { [url] in
            guard let data = try? JSONEncoder().encode(state) else { return }
            try? data.write(to: url, options: .atomic)
        }
    }

    func reset() {
        try? FileManager.default.removeItem(at: url)
    }
}
