import Foundation

/// The restaurant catalog. A factory (`mk`) derives each attribute vector from the
/// cuisine's base weights plus price-driven style and a few per-restaurant overrides,
/// so 40+ restaurants stay readable while every vector is rich enough to drive matching.
enum Restaurants {

    /// Compact factory. `extra` tunes specific taste dimensions per restaurant.
    private static func mk(
        _ id: String, _ name: String, _ cuisine: Cuisine, sub: String,
        city: String, hood: String, price: PriceLevel,
        lat: Double, lon: Double, occ: [Occasion],
        pop: Double, hist: Int, trending: Bool = false, landmark: Bool = false, michelin: Int = 0,
        dishes: [(String, String, Bool)], blurb: String,
        extra: [TasteDimension: Double] = [:]
    ) -> Restaurant {
        var dims = cuisine.dimensionWeights
        // Price → style axes.
        dims[.fineDining] = max(dims[.fineDining] ?? 0, price >= .upscale ? 0.55 + 0.15 * Double(price.rawValue - 3) : 0.15)
        dims[.casual] = max(dims[.casual] ?? 0, price <= .moderate ? 0.7 : 0.3)
        dims[.value] = max(dims[.value] ?? 0, price <= .moderate ? 0.65 : 0.25)
        // Per-restaurant overrides win.
        for (k, v) in extra { dims[k] = v }

        let dishObjs = dishes.enumerated().map { i, d in
            Dish(id: "\(id)-d\(i)", name: d.0, note: d.1, isSignature: d.2)
        }
        return Restaurant(
            id: id, name: name, cuisine: cuisine, subCuisine: sub,
            cityID: city, neighborhood: hood, price: price,
            coordinate: Coordinate(latitude: lat, longitude: lon),
            attributes: TasteVector(dims), occasions: Set(occ),
            popularity: pop, historicalCheckins: hist, isTrending: trending,
            isLandmark: landmark, michelinStars: michelin,
            dishes: dishObjs, blurb: blurb
        )
    }

    // MARK: Shanghai

    static let shanghai: [Restaurant] = [
        mk("sh-fuhehui", "Fu He Hui", .modernChinese, sub: "Vegetarian fine dining",
           city: "shanghai", hood: "Jing'an", price: .luxury, lat: 31.2260, lon: 121.4400,
           occ: [.dateNight, .celebration, .business], pop: 0.82, hist: 210, landmark: true, michelin: 1,
           dishes: [("Lotus & Chrysanthemum", "Signature tasting course", true), ("Bamboo Fungus Soup", "Delicate double-boiled broth", false)],
           blurb: "A serene temple to modern Chinese vegetarian cooking.",
           extra: [.novelty: 0.9, .atmosphere: 0.9, .authenticity: 0.7]),
        mk("sh-laozhengxing", "Lao Zheng Xing", .shanghainese, sub: "Classic hongshaorou",
           city: "shanghai", hood: "Huangpu", price: .moderate, lat: 31.2280, lon: 121.4820,
           occ: [.friends, .solo, .quickBite], pop: 0.71, hist: 640,
           dishes: [("Braised Pork Belly", "Sweet-savory hongshaorou", true), ("Drunken Crab", "Seasonal specialty", false)],
           blurb: "Century-old Shanghainese comfort food.",
           extra: [.authenticity: 0.9]),
        mk("sh-dintaifung", "Din Tai Fung", .shanghainese, sub: "Xiaolongbao",
           city: "shanghai", hood: "Xintiandi", price: .moderate, lat: 31.2200, lon: 121.4750,
           occ: [.friends, .quickBite, .business], pop: 0.95, hist: 980, landmark: true,
           dishes: [("Pork Xiaolongbao", "The benchmark soup dumpling", true), ("Truffle XLB", "Luxe seasonal version", false)],
           blurb: "Precision soup dumplings, universally loved."),
        mk("sh-haidilao", "Haidilao", .hotpot, sub: "Sichuan hot pot",
           city: "shanghai", hood: "Changning", price: .moderate, lat: 31.2190, lon: 121.4200,
           occ: [.friends, .lateNight, .celebration], pop: 0.93, hist: 1200,
           dishes: [("Spicy Mala Broth", "The classic half-and-half pot", true), ("Hand-pulled Noodles", "Tableside noodle dance", false)],
           blurb: "Theatrical hot pot with legendary service.",
           extra: [.spicy: 0.85, .atmosphere: 0.6]),
        mk("sh-linglong", "Ling Long", .modernChinese, sub: "New Chinese tasting",
           city: "shanghai", hood: "French Concession", price: .upscale, lat: 31.2130, lon: 121.4560,
           occ: [.dateNight, .celebration], pop: 0.68, hist: 95, trending: true, michelin: 1,
           dishes: [("Aged Duck", "Dry-aged, two ways", true), ("Sea Cucumber", "House XO", false)],
           blurb: "Chef Jason Liu's inventive, ingredient-driven Chinese.",
           extra: [.novelty: 0.92, .atmosphere: 0.8, .authenticity: 0.6]),
        mk("sh-yushang", "Yu Shang", .sichuan, sub: "Chengdu-style",
           city: "shanghai", hood: "Jing'an", price: .moderate, lat: 31.2240, lon: 121.4460,
           occ: [.friends, .cheapEats, .solo], pop: 0.64, hist: 88, trending: true,
           dishes: [("Mapo Tofu", "Numbing and deep", true), ("Water-boiled Fish", "Chili oil bath", false)],
           blurb: "A tiny room turning out ferocious, honest Sichuan.",
           extra: [.spicy: 0.95, .authenticity: 0.85, .value: 0.8]),
        mk("sh-hakkasan", "Hakkasan", .cantonese, sub: "Modern Cantonese",
           city: "shanghai", hood: "Huangpu", price: .luxury, lat: 31.2400, lon: 121.4900,
           occ: [.dateNight, .business, .celebration], pop: 0.77, hist: 430,
           dishes: [("Crispy Duck Salad", "Signature starter", true), ("Silver Cod", "Champagne & honey", false)],
           blurb: "Glamorous dim sum and Cantonese on the Bund.",
           extra: [.atmosphere: 0.9]),
        mk("sh-yunnanteng", "Teng Yunnan", .yunnan, sub: "Yunnan wild flavors",
           city: "shanghai", hood: "Xuhui", price: .moderate, lat: 31.1980, lon: 121.4400,
           occ: [.friends, .explore, .solo], pop: 0.52, hist: 61,
           dishes: [("Wild Mushroom Pot", "Seasonal fungi", true), ("Crossing-bridge Noodles", "Yunnan classic", false)],
           blurb: "Herbaceous, mushroom-forward cooking from the southwest.",
           extra: [.novelty: 0.8, .authenticity: 0.85, .value: 0.7]),
        mk("sh-egg", "EGG", .cafe, sub: "All-day café",
           city: "shanghai", hood: "Changning", price: .moderate, lat: 31.2170, lon: 121.4300,
           occ: [.coffee, .solo, .friends], pop: 0.6, hist: 240,
           dishes: [("Shakshuka", "Weekend staple", true), ("Flat White", "House espresso", false)],
           blurb: "Bright brunch and dependable coffee.",
           extra: [.coffee: 0.9, .atmosphere: 0.7]),
        mk("sh-seesaw", "Seesaw Coffee", .cafe, sub: "Specialty roaster",
           city: "shanghai", hood: "Jing'an", price: .budget, lat: 31.2250, lon: 121.4480,
           occ: [.coffee, .quickBite, .solo], pop: 0.66, hist: 520,
           dishes: [("Single-origin Pour Over", "Rotating beans", true), ("Oat Latte", "House favorite", false)],
           blurb: "Homegrown specialty coffee, everywhere for a reason.",
           extra: [.coffee: 0.95, .value: 0.7]),
        mk("sh-raganddagger", "Rag & Dagger", .italian, sub: "Wood-fired",
           city: "shanghai", hood: "French Concession", price: .upscale, lat: 31.2100, lon: 121.4550,
           occ: [.dateNight, .friends], pop: 0.58, hist: 130,
           dishes: [("Nduja Pizza", "Spicy & blistered", true), ("Cacio e Pepe", "Simple, exact", false)],
           blurb: "Neighborhood Italian with a serious wine list.",
           extra: [.atmosphere: 0.8]),
        mk("sh-sushioomori", "Sushi Oomori", .sushi, sub: "Edomae omakase",
           city: "shanghai", hood: "Pudong", price: .luxury, lat: 31.2350, lon: 121.5050,
           occ: [.dateNight, .celebration, .business], pop: 0.7, hist: 150, michelin: 1,
           dishes: [("Otoro", "Aged fatty tuna", true), ("Uni Handroll", "Hokkaido bafun", false)],
           blurb: "Meticulous Edomae omakase, flown-in fish.",
           extra: [.fineDining: 0.9, .authenticity: 0.85]),
        mk("sh-ramenishikawa", "Ishikawa Ramen", .ramen, sub: "Tonkotsu",
           city: "shanghai", hood: "Hongkou", price: .budget, lat: 31.2700, lon: 121.5050,
           occ: [.quickBite, .lateNight, .cheapEats, .solo], pop: 0.55, hist: 74, trending: true,
           dishes: [("Tonkotsu Ramen", "18-hour pork broth", true), ("Ajitama", "Marinated egg", false)],
           blurb: "A slurpable bowl worth the queue.",
           extra: [.value: 0.85]),
        mk("sh-pudongtea", "Pudong Tea House", .dessert, sub: "Tea & sweets",
           city: "shanghai", hood: "Pudong", price: .moderate, lat: 31.2300, lon: 121.5100,
           occ: [.dessert, .coffee, .solo], pop: 0.48, hist: 190,
           dishes: [("Osmanthus Jelly", "Floral & light", true), ("Matcha Roll", "Not too sweet", false)],
           blurb: "Quiet afternoons over tea and delicate sweets.",
           extra: [.dessert: 0.9, .atmosphere: 0.75])
    ]

    // MARK: Seoul

    static let seoul: [Restaurant] = [
        mk("se-mingles", "Mingles", .modernChinese, sub: "New Korean tasting",
           city: "seoul", hood: "Gangnam", price: .luxury, lat: 37.5270, lon: 127.0400,
           occ: [.dateNight, .celebration, .business], pop: 0.8, hist: 260, landmark: true, michelin: 2,
           dishes: [("Jang Trio", "Fermented sauces flight", true), ("Aged Beef", "Charcoal-kissed", false)],
           blurb: "Korea's benchmark for refined, fermentation-driven cooking.",
           extra: [.korean: 1, .novelty: 0.9, .atmosphere: 0.85, .authenticity: 0.8, .chinese: 0]),
        mk("se-jungsik", "Jungsik", .korean, sub: "Nouveau Korean",
           city: "seoul", hood: "Gangnam", price: .luxury, lat: 37.5240, lon: 127.0420,
           occ: [.dateNight, .celebration], pop: 0.74, hist: 210, michelin: 2,
           dishes: [("Bibimbap, reimagined", "Signature", true), ("Sea Urchin Rice", "Umami bomb", false)],
           blurb: "Precise, modern Korean that travels the world.",
           extra: [.novelty: 0.88, .fineDining: 0.9]),
        mk("se-gwangjang", "Gwangjang Bindaetteok", .korean, sub: "Market street food",
           city: "seoul", hood: "Jongno", price: .budget, lat: 37.5700, lon: 126.9997,
           occ: [.cheapEats, .quickBite, .explore, .solo], pop: 0.9, hist: 1500, landmark: true,
           dishes: [("Bindaetteok", "Mung bean pancake", true), ("Mayak Gimbap", "Addictive mini rolls", false)],
           blurb: "The beating heart of Seoul market eating.",
           extra: [.streetFood: 0.95, .value: 0.9, .authenticity: 0.95]),
        mk("se-parkhae", "Parkhae Jip", .koreanBBQ, sub: "Charcoal galbi",
           city: "seoul", hood: "Mapo", price: .moderate, lat: 37.5460, lon: 126.9500,
           occ: [.friends, .celebration, .lateNight], pop: 0.72, hist: 540,
           dishes: [("Marinated Galbi", "Charcoal-grilled short rib", true), ("Doenjang Jjigae", "Comfort stew", false)],
           blurb: "Smoke, sizzle, and soju with the crew.",
           extra: [.atmosphere: 0.7, .spicy: 0.4]),
        mk("se-onjium", "Onjium", .korean, sub: "Royal court cuisine",
           city: "seoul", hood: "Jongno", price: .upscale, lat: 37.5780, lon: 126.9720,
           occ: [.dateNight, .business], pop: 0.6, hist: 120, michelin: 1,
           dishes: [("Gujeolpan", "Nine-section platter", true), ("Sinseollo", "Royal hot pot", false)],
           blurb: "Scholarly revival of Joseon-era royal dishes.",
           extra: [.authenticity: 0.95, .atmosphere: 0.8]),
        mk("se-seongsucoffee", "Seongsu Coffee Lab", .cafe, sub: "Third-wave",
           city: "seoul", hood: "Seongsu", price: .moderate, lat: 37.5445, lon: 127.0560,
           occ: [.coffee, .solo, .friends], pop: 0.7, hist: 180, trending: true,
           dishes: [("Cold Brew Tonic", "Bright & fizzy", true), ("Cortado", "Balanced", false)],
           blurb: "The cafe that defines Seongsu's warehouse-chic scene.",
           extra: [.coffee: 0.95, .atmosphere: 0.85, .novelty: 0.6]),
        mk("se-eomeoni", "Eomeoni Sonmandu", .korean, sub: "Handmade dumplings",
           city: "seoul", hood: "Hongdae", price: .budget, lat: 37.5560, lon: 126.9230,
           occ: [.cheapEats, .quickBite, .solo], pop: 0.58, hist: 66, trending: true,
           dishes: [("Kimchi Mandu", "Fermented kick", true), ("Tteok Mandu Guk", "Rice-cake soup", false)],
           blurb: "Grandma-style dumplings, folded to order.",
           extra: [.value: 0.9, .authenticity: 0.85, .spicy: 0.4]),
        mk("se-itaewontaco", "Vatos Urban Tacos", .mexican, sub: "Korean-Mexican",
           city: "seoul", hood: "Itaewon", price: .moderate, lat: 37.5340, lon: 126.9940,
           occ: [.friends, .lateNight, .quickBite], pop: 0.64, hist: 340,
           dishes: [("Kimchi Carnitas Fries", "Cult favorite", true), ("Galbi Taco", "Fusion done right", false)],
           blurb: "Rowdy, delicious Korean-Mexican mashups.",
           extra: [.novelty: 0.7, .value: 0.7]),
        mk("se-nudake", "Nudake", .dessert, sub: "Sculptural pastry",
           city: "seoul", hood: "Gangnam", price: .moderate, lat: 37.5250, lon: 127.0230,
           occ: [.dessert, .coffee, .dateNight], pop: 0.68, hist: 150, trending: true,
           dishes: [("Peak Croissant", "Matcha-filled monolith", true), ("Cream Cake", "Art on a plate", false)],
           blurb: "Pastry as sculpture — as photogenic as it is good.",
           extra: [.dessert: 0.95, .novelty: 0.85, .atmosphere: 0.8])
    ]

    // MARK: San Francisco

    static let sf: [Restaurant] = [
        mk("sf-benu", "Benu", .modernChinese, sub: "Asian-American tasting",
           city: "sf", hood: "SoMa", price: .luxury, lat: 37.7850, lon: -122.3990,
           occ: [.celebration, .dateNight, .business], pop: 0.83, hist: 300, landmark: true, michelin: 3,
           dishes: [("Faux Shark Fin Soup", "Iconic course", true), ("Thousand-year-old Quail Egg", "Signature bite", false)],
           blurb: "Corey Lee's three-star Asian-American tour de force.",
           extra: [.novelty: 0.95, .fineDining: 0.95, .atmosphere: 0.85]),
        mk("sf-zuni", "Zuni Café", .californian, sub: "Market-driven",
           city: "sf", hood: "Hayes Valley", price: .upscale, lat: 37.7740, lon: -122.4230,
           occ: [.dateNight, .friends, .business], pop: 0.8, hist: 900, landmark: true,
           dishes: [("Roast Chicken for Two", "The famous bird", true), ("Caesar Salad", "Perfected", false)],
           blurb: "A San Francisco institution with a chicken worth the wait.",
           extra: [.atmosphere: 0.85, .authenticity: 0.7]),
        mk("sf-lataqueria", "La Taqueria", .mexican, sub: "Mission burritos",
           city: "sf", hood: "Mission", price: .budget, lat: 37.7510, lon: -122.4180,
           occ: [.cheapEats, .quickBite, .solo, .friends], pop: 0.9, hist: 1300, landmark: true,
           dishes: [("Carnitas Burrito", "No rice, all flavor", true), ("Al Pastor Taco", "Griddled edges", false)],
           blurb: "The Mission burrito benchmark, full stop.",
           extra: [.streetFood: 0.9, .value: 0.9, .authenticity: 0.9]),
        mk("sf-statebird", "State Bird Provisions", .californian, sub: "Dim-sum-style small plates",
           city: "sf", hood: "Fillmore", price: .upscale, lat: 37.7830, lon: -122.4330,
           occ: [.friends, .dateNight, .explore], pop: 0.76, hist: 260, trending: false,
           dishes: [("State Bird", "Quail with provisions", true), ("Cart Surprises", "Ever-changing", false)],
           blurb: "Playful, cart-driven Californian that started a trend.",
           extra: [.novelty: 0.9, .atmosphere: 0.75]),
        mk("sf-sightglass", "Sightglass Coffee", .cafe, sub: "Roaster café",
           city: "sf", hood: "SoMa", price: .moderate, lat: 37.7770, lon: -122.4090,
           occ: [.coffee, .solo, .quickBite], pop: 0.72, hist: 610,
           dishes: [("Owl's Howl Espresso", "House blend", true), ("Pour Over", "Rotating single origin", false)],
           blurb: "Sunlit, industrial temple to good coffee.",
           extra: [.coffee: 0.95, .atmosphere: 0.7]),
        mk("sf-nari", "Nari", .thai, sub: "Modern Thai",
           city: "sf", hood: "Japantown", price: .upscale, lat: 37.7850, lon: -122.4310,
           occ: [.dateNight, .friends, .explore], pop: 0.66, hist: 140, trending: true,
           dishes: [("Fish Curry Custard", "Silky & fragrant", true), ("Crab Curry", "Rich & spicy", false)],
           blurb: "Chef Pim's bold, modern take on Thai flavor.",
           extra: [.spicy: 0.75, .novelty: 0.8, .authenticity: 0.7, .mexican: 0]),
        mk("sf-tartine", "Tartine Bakery", .bakery, sub: "Country bread & pastry",
           city: "sf", hood: "Mission", price: .moderate, lat: 37.7614, lon: -122.4241,
           occ: [.coffee, .quickBite, .dessert, .solo], pop: 0.88, hist: 1100, landmark: true,
           dishes: [("Morning Bun", "Flaky, citrus sugar", true), ("Country Loaf", "The famous crumb", false)],
           blurb: "The bakery that reshaped American bread.",
           extra: [.dessert: 0.8, .value: 0.6]),
        mk("sf-marufuku", "Marufuku Ramen", .ramen, sub: "Hakata tonkotsu",
           city: "sf", hood: "Japantown", price: .moderate, lat: 37.7852, lon: -122.4300,
           occ: [.quickBite, .friends, .lateNight, .solo], pop: 0.74, hist: 420,
           dishes: [("Hakata Tonkotsu", "Ultra-creamy broth", true), ("Spicy Tan Tan", "Sesame heat", false)],
           blurb: "Silky Hakata-style bowls with a nightly line.",
           extra: [.value: 0.7])
    ]

    // MARK: New York

    static let nyc: [Restaurant] = [
        mk("ny-atomix", "Atomix", .korean, sub: "Progressive Korean tasting",
           city: "nyc", hood: "Flatiron", price: .luxury, lat: 40.7440, lon: -73.9840,
           occ: [.celebration, .dateNight, .business], pop: 0.86, hist: 240, landmark: true, michelin: 2,
           dishes: [("Card-guided Courses", "Story per plate", true), ("Aged Fish", "Precise & deep", false)],
           blurb: "The world's-best-list Korean tasting counter.",
           extra: [.novelty: 0.95, .fineDining: 0.95, .atmosphere: 0.9, .authenticity: 0.75]),
        mk("ny-lucali", "Lucali", .italian, sub: "Brooklyn pizza",
           city: "nyc", hood: "Williamsburg", price: .moderate, lat: 40.6800, lon: -73.9990,
           occ: [.dateNight, .friends], pop: 0.85, hist: 700, landmark: true,
           dishes: [("Margherita Pie", "Blistered, candle-lit", true), ("Calzone", "Cult favorite", false)],
           blurb: "Candlelit, cash-only pizza worth every minute in line.",
           extra: [.atmosphere: 0.85, .authenticity: 0.8, .value: 0.6]),
        mk("ny-xianfamous", "Xi'an Famous Foods", .modernChinese, sub: "Hand-ripped noodles",
           city: "nyc", hood: "Chinatown", price: .budget, lat: 40.7150, lon: -73.9970,
           occ: [.cheapEats, .quickBite, .solo], pop: 0.88, hist: 1400,
           dishes: [("Spicy Cumin Lamb Noodles", "Hand-ripped, fiery", true), ("Liang Pi", "Cold skin noodles", false)],
           blurb: "Fiery Xi'an street food that conquered the city.",
           extra: [.spicy: 0.85, .streetFood: 0.9, .value: 0.9, .authenticity: 0.85]),
        mk("ny-villageeast", "Kanoyama", .sushi, sub: "Neighborhood omakase",
           city: "nyc", hood: "East Village", price: .upscale, lat: 40.7290, lon: -73.9860,
           occ: [.dateNight, .solo, .business], pop: 0.68, hist: 330,
           dishes: [("Omakase Counter", "Seasonal fish", true), ("Uni Flight", "Three origins", false)],
           blurb: "Underrated East Village sushi with serious fish.",
           extra: [.authenticity: 0.85, .fineDining: 0.7]),
        mk("ny-abraco", "Abraço", .cafe, sub: "Espresso & snacks",
           city: "nyc", hood: "East Village", price: .moderate, lat: 40.7270, lon: -73.9850,
           occ: [.coffee, .quickBite, .solo], pop: 0.7, hist: 380,
           dishes: [("Olive Cake", "Savory-sweet", true), ("Espresso", "Dark & syrupy", false)],
           blurb: "A tiny counter with a devoted coffee following.",
           extra: [.coffee: 0.95, .atmosphere: 0.7]),
        mk("ny-superiority", "Superiority Burger", .american, sub: "Veggie burgers",
           city: "nyc", hood: "East Village", price: .budget, lat: 40.7250, lon: -73.9820,
           occ: [.cheapEats, .quickBite, .solo, .friends], pop: 0.76, hist: 260, trending: true,
           dishes: [("Superiority Burger", "Legendary veggie patty", true), ("Burnt Broccoli Salad", "Cult side", false)],
           blurb: "A little counter with a huge, deserved reputation.",
           extra: [.value: 0.85, .novelty: 0.7]),
        mk("ny-rezdora", "Rezdora", .italian, sub: "Emilia-Romagna pasta",
           city: "nyc", hood: "Flatiron", price: .upscale, lat: 40.7380, lon: -73.9880,
           occ: [.dateNight, .friends, .celebration], pop: 0.82, hist: 300, trending: true, michelin: 1,
           dishes: [("Ugly But Good Tortellini", "Signature", true), ("Tortellini in Brodo", "Comfort", false)],
           blurb: "Handmade pasta that keeps the whole city queuing.",
           extra: [.atmosphere: 0.8, .authenticity: 0.85]),
        mk("ny-veselka", "Veselka", .american, sub: "Ukrainian diner",
           city: "nyc", hood: "East Village", price: .budget, lat: 40.7290, lon: -73.9880,
           occ: [.lateNight, .cheapEats, .solo, .friends], pop: 0.8, hist: 1600, landmark: true,
           dishes: [("Pierogi", "Boiled or fried", true), ("Borscht", "Ruby & warming", false)],
           blurb: "24-hour Ukrainian comfort, an East Village constant.",
           extra: [.value: 0.85, .authenticity: 0.8, .atmosphere: 0.6])
    ]

    // MARK: Tokyo (secondary city — depth for the Food Passport)

    static let tokyo: [Restaurant] = [
        mk("tk-sukiyabashi", "Sushi Saito", .sushi, sub: "Edomae omakase",
           city: "tokyo", hood: "Ginza", price: .luxury, lat: 35.6720, lon: 139.7370,
           occ: [.celebration, .business, .dateNight], pop: 0.88, hist: 190, landmark: true, michelin: 3,
           dishes: [("Tuna Trio", "Akami to otoro", true), ("Anago", "Melting sea eel", false)],
           blurb: "Frequently called the best sushi on earth.",
           extra: [.authenticity: 0.98, .fineDining: 0.98]),
        mk("tk-ichiran", "Ichiran Shibuya", .ramen, sub: "Tonkotsu solo booths",
           city: "tokyo", hood: "Shibuya", price: .budget, lat: 35.6595, lon: 139.7005,
           occ: [.quickBite, .lateNight, .solo, .cheapEats], pop: 0.9, hist: 2000,
           dishes: [("Classic Tonkotsu", "Customizable bowl", true), ("Kae-dama", "Noodle refill", false)],
           blurb: "Focused, solo-booth ramen open all hours.",
           extra: [.value: 0.85]),
        mk("tk-nakameguro", "Nakameguro Coffee", .cafe, sub: "Pour-over bar",
           city: "tokyo", hood: "Nakameguro", price: .moderate, lat: 35.6440, lon: 139.6990,
           occ: [.coffee, .solo, .friends], pop: 0.66, hist: 210,
           dishes: [("Hand Drip", "Single origin", true), ("Matcha Latte", "Stone-ground", false)],
           blurb: "Canal-side calm and immaculate pour-overs.",
           extra: [.coffee: 0.95, .atmosphere: 0.85]),
        mk("tk-birdland", "Birdland", .izakaya, sub: "Yakitori counter",
           city: "tokyo", hood: "Ginza", price: .upscale, lat: 35.6715, lon: 139.7640,
           occ: [.dateNight, .friends, .business], pop: 0.74, hist: 260, michelin: 1,
           dishes: [("Chicken Liver", "Silken skewer", true), ("Oyako Don", "Finale rice bowl", false)],
           blurb: "Michelin yakitori that elevates every skewer.",
           extra: [.authenticity: 0.9, .atmosphere: 0.8])
    ]

    static let all: [Restaurant] = shanghai + seoul + sf + nyc + tokyo

    static func by(id: String) -> Restaurant? { all.first { $0.id == id } }
}
